<?php
function ajax_review_menu() {
  $items['ajax-code-review/%/%'] = array (
  'access arguments' => array('access content'),
  'page callback' => 'ajax_review_ajax_callback',
  'page arguments' => array(1,2),
  'type' => MENU_CALLBACK,
  );
  return $items;
}

function ajax_review_ajax_callback($js, $node_id) {
  $node = node_load($node_id);

  if ($js == 'nojs') {
    drupal_goto('node/' . $node ->nid);
  }

  $build = node_view($node);
  $html = render($build);

  $commands = array();
  $commands[] = ajax_command_html('#code-review-ajax-wrapper', $html);

  print ajax_render($commands);
  exit;
}
