<?php

function shift_cypher_menu(){
    $items = array();
    $items['shift_cypher'] = array(
        'title' => 'Shift Cypher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cypher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['shift_cypher_success_page'] = array(
        'title' => 'Success',
        'page callback' => 'shift_cypher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function shift_cypher_form(){
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => 'How many spaces would you like to shift?',
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => 'Shift left or right?',
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
    );
    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => 'Enter a phrase to shift! (Only letters, spaces, and punctuation allowed!)',
        '#element_validate' => array('element_validate_phrase'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'GO!',
    );
    return $form;
}

function element_validate_direction($element) {
    // $user_direction = strtolower($element['#value']);
    // $directions = array('left', 'right');
    //
    // if(!in_array($user_direction, $directions)) {
    //     form_set_error('shift_direction', t('Please enter a valid direction.'));
    // }

    // $direction = strtolower($element['#value']);
    //
    // if($direction != 'left' || $direction != 'right'){
    //     form_set_error('shift_direction', t('Please enter a valid direction!'));
    // }

    $direction = strtolower($element['#value']);

    if($direction !== 'left' && $direction !== 'right'){
        form_error($element, 'Enter a valid direction!');
    }
}

function element_validate_phrase($element) {
    $phrase = strtolower($element['#value']);

    if(!preg_match("/^[a-zA-Z\ .'s]*$/", $phrase)) {
        form_set_error('phrase', t('Only letters and punctuation!'));
    }
}

function shift_cypher_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    $shift_direction = $form_state['values']['shift_direction'];
    $phrase = $form_state['values']['phrase'];

    $form_state['redirect'] = 'shift_cypher_success_page';
}

function shift_cypher_success() {
    echo 'nice';
}
